package pokedex

type GenderKind int

const (
	Both GenderKind = iota
	MaleOnly
	FemaleOnly
	Genderless
)

type Species struct {
	Number      int
	Name        string
	DisplayName string
	Gender      GenderKind
}

var kanto = []Species{
	{Number: 1, Name: "bulbasaur", DisplayName: "Bulbasaur", Gender: Both},
	{Number: 2, Name: "ivysaur", DisplayName: "Ivysaur", Gender: Both},
	{Number: 3, Name: "venusaur", DisplayName: "Venusaur", Gender: Both},
	{Number: 4, Name: "charmander", DisplayName: "Charmander", Gender: Both},
	{Number: 5, Name: "charmeleon", DisplayName: "Charmeleon", Gender: Both},
	{Number: 6, Name: "charizard", DisplayName: "Charizard", Gender: Both},
	{Number: 7, Name: "squirtle", DisplayName: "Squirtle", Gender: Both},
	{Number: 8, Name: "wartortle", DisplayName: "Wartortle", Gender: Both},
	{Number: 9, Name: "blastoise", DisplayName: "Blastoise", Gender: Both},
	{Number: 10, Name: "caterpie", DisplayName: "Caterpie", Gender: Both},
	{Number: 11, Name: "metapod", DisplayName: "Metapod", Gender: Both},
	{Number: 12, Name: "butterfree", DisplayName: "Butterfree", Gender: Both},
	{Number: 13, Name: "weedle", DisplayName: "Weedle", Gender: Both},
	{Number: 14, Name: "kakuna", DisplayName: "Kakuna", Gender: Both},
	{Number: 15, Name: "beedrill", DisplayName: "Beedrill", Gender: Both},
	{Number: 16, Name: "pidgey", DisplayName: "Pidgey", Gender: Both},
	{Number: 17, Name: "pidgeotto", DisplayName: "Pidgeotto", Gender: Both},
	{Number: 18, Name: "pidgeot", DisplayName: "Pidgeot", Gender: Both},
	{Number: 19, Name: "rattata", DisplayName: "Rattata", Gender: Both},
	{Number: 20, Name: "raticate", DisplayName: "Raticate", Gender: Both},
	{Number: 21, Name: "spearow", DisplayName: "Spearow", Gender: Both},
	{Number: 22, Name: "fearow", DisplayName: "Fearow", Gender: Both},
	{Number: 23, Name: "ekans", DisplayName: "Ekans", Gender: Both},
	{Number: 24, Name: "arbok", DisplayName: "Arbok", Gender: Both},
	{Number: 25, Name: "pikachu", DisplayName: "Pikachu", Gender: Both},
	{Number: 26, Name: "raichu", DisplayName: "Raichu", Gender: Both},
	{Number: 27, Name: "sandshrew", DisplayName: "Sandshrew", Gender: Both},
	{Number: 28, Name: "sandslash", DisplayName: "Sandslash", Gender: Both},
	{Number: 29, Name: "nidoran-f", DisplayName: "Nidoran♀", Gender: FemaleOnly},
	{Number: 30, Name: "nidorina", DisplayName: "Nidorina", Gender: FemaleOnly},
	{Number: 31, Name: "nidoqueen", DisplayName: "Nidoqueen", Gender: FemaleOnly},
	{Number: 32, Name: "nidoran-m", DisplayName: "Nidoran♂", Gender: MaleOnly},
	{Number: 33, Name: "nidorino", DisplayName: "Nidorino", Gender: MaleOnly},
	{Number: 34, Name: "nidoking", DisplayName: "Nidoking", Gender: MaleOnly},
	{Number: 35, Name: "clefairy", DisplayName: "Clefairy", Gender: Both},
	{Number: 36, Name: "clefable", DisplayName: "Clefable", Gender: Both},
	{Number: 37, Name: "vulpix", DisplayName: "Vulpix", Gender: Both},
	{Number: 38, Name: "ninetales", DisplayName: "Ninetales", Gender: Both},
	{Number: 39, Name: "jigglypuff", DisplayName: "Jigglypuff", Gender: Both},
	{Number: 40, Name: "wigglytuff", DisplayName: "Wigglytuff", Gender: Both},
	{Number: 41, Name: "zubat", DisplayName: "Zubat", Gender: Both},
	{Number: 42, Name: "golbat", DisplayName: "Golbat", Gender: Both},
	{Number: 43, Name: "oddish", DisplayName: "Oddish", Gender: Both},
	{Number: 44, Name: "gloom", DisplayName: "Gloom", Gender: Both},
	{Number: 45, Name: "vileplume", DisplayName: "Vileplume", Gender: Both},
	{Number: 46, Name: "paras", DisplayName: "Paras", Gender: Both},
	{Number: 47, Name: "parasect", DisplayName: "Parasect", Gender: Both},
	{Number: 48, Name: "venonat", DisplayName: "Venonat", Gender: Both},
	{Number: 49, Name: "venomoth", DisplayName: "Venomoth", Gender: Both},
	{Number: 50, Name: "diglett", DisplayName: "Diglett", Gender: Both},
	{Number: 51, Name: "dugtrio", DisplayName: "Dugtrio", Gender: Both},
	{Number: 52, Name: "meowth", DisplayName: "Meowth", Gender: Both},
	{Number: 53, Name: "persian", DisplayName: "Persian", Gender: Both},
	{Number: 54, Name: "psyduck", DisplayName: "Psyduck", Gender: Both},
	{Number: 55, Name: "golduck", DisplayName: "Golduck", Gender: Both},
	{Number: 56, Name: "mankey", DisplayName: "Mankey", Gender: Both},
	{Number: 57, Name: "primeape", DisplayName: "Primeape", Gender: Both},
	{Number: 58, Name: "growlithe", DisplayName: "Growlithe", Gender: Both},
	{Number: 59, Name: "arcanine", DisplayName: "Arcanine", Gender: Both},
	{Number: 60, Name: "poliwag", DisplayName: "Poliwag", Gender: Both},
	{Number: 61, Name: "poliwhirl", DisplayName: "Poliwhirl", Gender: Both},
	{Number: 62, Name: "poliwrath", DisplayName: "Poliwrath", Gender: Both},
	{Number: 63, Name: "abra", DisplayName: "Abra", Gender: Both},
	{Number: 64, Name: "kadabra", DisplayName: "Kadabra", Gender: Both},
	{Number: 65, Name: "alakazam", DisplayName: "Alakazam", Gender: Both},
	{Number: 66, Name: "machop", DisplayName: "Machop", Gender: Both},
	{Number: 67, Name: "machoke", DisplayName: "Machoke", Gender: Both},
	{Number: 68, Name: "machamp", DisplayName: "Machamp", Gender: Both},
	{Number: 69, Name: "bellsprout", DisplayName: "Bellsprout", Gender: Both},
	{Number: 70, Name: "weepinbell", DisplayName: "Weepinbell", Gender: Both},
	{Number: 71, Name: "victreebel", DisplayName: "Victreebel", Gender: Both},
	{Number: 72, Name: "tentacool", DisplayName: "Tentacool", Gender: Both},
	{Number: 73, Name: "tentacruel", DisplayName: "Tentacruel", Gender: Both},
	{Number: 74, Name: "geodude", DisplayName: "Geodude", Gender: Both},
	{Number: 75, Name: "graveler", DisplayName: "Graveler", Gender: Both},
	{Number: 76, Name: "golem", DisplayName: "Golem", Gender: Both},
	{Number: 77, Name: "ponyta", DisplayName: "Ponyta", Gender: Both},
	{Number: 78, Name: "rapidash", DisplayName: "Rapidash", Gender: Both},
	{Number: 79, Name: "slowpoke", DisplayName: "Slowpoke", Gender: Both},
	{Number: 80, Name: "slowbro", DisplayName: "Slowbro", Gender: Both},
	{Number: 81, Name: "magnemite", DisplayName: "Magnemite", Gender: Genderless},
	{Number: 82, Name: "magneton", DisplayName: "Magneton", Gender: Genderless},
	{Number: 83, Name: "farfetchd", DisplayName: "Farfetch’d", Gender: Both},
	{Number: 84, Name: "doduo", DisplayName: "Doduo", Gender: Both},
	{Number: 85, Name: "dodrio", DisplayName: "Dodrio", Gender: Both},
	{Number: 86, Name: "seel", DisplayName: "Seel", Gender: Both},
	{Number: 87, Name: "dewgong", DisplayName: "Dewgong", Gender: Both},
	{Number: 88, Name: "grimer", DisplayName: "Grimer", Gender: Both},
	{Number: 89, Name: "muk", DisplayName: "Muk", Gender: Both},
	{Number: 90, Name: "shellder", DisplayName: "Shellder", Gender: Both},
	{Number: 91, Name: "cloyster", DisplayName: "Cloyster", Gender: Both},
	{Number: 92, Name: "gastly", DisplayName: "Gastly", Gender: Both},
	{Number: 93, Name: "haunter", DisplayName: "Haunter", Gender: Both},
	{Number: 94, Name: "gengar", DisplayName: "Gengar", Gender: Both},
	{Number: 95, Name: "onix", DisplayName: "Onix", Gender: Both},
	{Number: 96, Name: "drowzee", DisplayName: "Drowzee", Gender: Both},
	{Number: 97, Name: "hypno", DisplayName: "Hypno", Gender: Both},
	{Number: 98, Name: "krabby", DisplayName: "Krabby", Gender: Both},
	{Number: 99, Name: "kingler", DisplayName: "Kingler", Gender: Both},
	{Number: 100, Name: "voltorb", DisplayName: "Voltorb", Gender: Genderless},
	{Number: 101, Name: "electrode", DisplayName: "Electrode", Gender: Genderless},
	{Number: 102, Name: "exeggcute", DisplayName: "Exeggcute", Gender: Both},
	{Number: 103, Name: "exeggutor", DisplayName: "Exeggutor", Gender: Both},
	{Number: 104, Name: "cubone", DisplayName: "Cubone", Gender: Both},
	{Number: 105, Name: "marowak", DisplayName: "Marowak", Gender: Both},
	{Number: 106, Name: "hitmonlee", DisplayName: "Hitmonlee", Gender: MaleOnly},
	{Number: 107, Name: "hitmonchan", DisplayName: "Hitmonchan", Gender: MaleOnly},
	{Number: 108, Name: "lickitung", DisplayName: "Lickitung", Gender: Both},
	{Number: 109, Name: "koffing", DisplayName: "Koffing", Gender: Both},
	{Number: 110, Name: "weezing", DisplayName: "Weezing", Gender: Both},
	{Number: 111, Name: "rhyhorn", DisplayName: "Rhyhorn", Gender: Both},
	{Number: 112, Name: "rhydon", DisplayName: "Rhydon", Gender: Both},
	{Number: 113, Name: "chansey", DisplayName: "Chansey", Gender: FemaleOnly},
	{Number: 114, Name: "tangela", DisplayName: "Tangela", Gender: Both},
	{Number: 115, Name: "kangaskhan", DisplayName: "Kangaskhan", Gender: FemaleOnly},
	{Number: 116, Name: "horsea", DisplayName: "Horsea", Gender: Both},
	{Number: 117, Name: "seadra", DisplayName: "Seadra", Gender: Both},
	{Number: 118, Name: "goldeen", DisplayName: "Goldeen", Gender: Both},
	{Number: 119, Name: "seaking", DisplayName: "Seaking", Gender: Both},
	{Number: 120, Name: "staryu", DisplayName: "Staryu", Gender: Genderless},
	{Number: 121, Name: "starmie", DisplayName: "Starmie", Gender: Genderless},
	{Number: 122, Name: "mr-mime", DisplayName: "Mr. Mime", Gender: Both},
	{Number: 123, Name: "scyther", DisplayName: "Scyther", Gender: Both},
	{Number: 124, Name: "jynx", DisplayName: "Jynx", Gender: FemaleOnly},
	{Number: 125, Name: "electabuzz", DisplayName: "Electabuzz", Gender: Both},
	{Number: 126, Name: "magmar", DisplayName: "Magmar", Gender: Both},
	{Number: 127, Name: "pinsir", DisplayName: "Pinsir", Gender: Both},
	{Number: 128, Name: "tauros", DisplayName: "Tauros", Gender: MaleOnly},
	{Number: 129, Name: "magikarp", DisplayName: "Magikarp", Gender: Both},
	{Number: 130, Name: "gyarados", DisplayName: "Gyarados", Gender: Both},
	{Number: 131, Name: "lapras", DisplayName: "Lapras", Gender: Both},
	{Number: 132, Name: "ditto", DisplayName: "Ditto", Gender: Genderless},
	{Number: 133, Name: "eevee", DisplayName: "Eevee", Gender: Both},
	{Number: 134, Name: "vaporeon", DisplayName: "Vaporeon", Gender: Both},
	{Number: 135, Name: "jolteon", DisplayName: "Jolteon", Gender: Both},
	{Number: 136, Name: "flareon", DisplayName: "Flareon", Gender: Both},
	{Number: 137, Name: "porygon", DisplayName: "Porygon", Gender: Genderless},
	{Number: 138, Name: "omanyte", DisplayName: "Omanyte", Gender: Both},
	{Number: 139, Name: "omastar", DisplayName: "Omastar", Gender: Both},
	{Number: 140, Name: "kabuto", DisplayName: "Kabuto", Gender: Both},
	{Number: 141, Name: "kabutops", DisplayName: "Kabutops", Gender: Both},
	{Number: 142, Name: "aerodactyl", DisplayName: "Aerodactyl", Gender: Both},
	{Number: 143, Name: "snorlax", DisplayName: "Snorlax", Gender: Both},
	{Number: 144, Name: "articuno", DisplayName: "Articuno", Gender: Genderless},
	{Number: 145, Name: "zapdos", DisplayName: "Zapdos", Gender: Genderless},
	{Number: 146, Name: "moltres", DisplayName: "Moltres", Gender: Genderless},
	{Number: 147, Name: "dratini", DisplayName: "Dratini", Gender: Both},
	{Number: 148, Name: "dragonair", DisplayName: "Dragonair", Gender: Both},
	{Number: 149, Name: "dragonite", DisplayName: "Dragonite", Gender: Both},
	{Number: 150, Name: "mewtwo", DisplayName: "Mewtwo", Gender: Genderless},
	{Number: 151, Name: "mew", DisplayName: "Mew", Gender: Genderless},
}

func Len() int {
	return len(kanto)
}

func At(i int) Species {
	return kanto[i]
}

func All() []Species {
	out := make([]Species, len(kanto))
	copy(out, kanto)

	return out
}
